/**
 * @file queued_sink.hpp
 * @brief Asynchronous (queued) decorator for any ILogSink
 *
 * Wraps a slow or lock-sensitive sink (MQTT, file, network) behind a bounded
 * in-memory queue. write() only deep-copies the message into the queue and
 * returns - it never performs I/O and never takes any lock other than its own
 * queue mutex. The wrapped sink runs from poll(), either called explicitly by
 * the application or driven by the optional built-in FreeRTOS drain task.
 *
 * Why this exists: Logger::logImpl() holds the global Logger mutex while
 * calling sink->write(). A sink that synchronously publishes over MQTT from
 * write() can deadlock: same-thread re-entry into a client lock held by the
 * caller, or a cross-task lock-order inversion between the Logger mutex and
 * the MQTT client mutex. An enqueue-only write() breaks every such cycle
 * structurally.
 *
 * Overflow policy: drop-oldest. The number of dropped messages is available
 * via droppedCount() so consumers can surface loss.
 *
 * Feedback protection: log lines emitted by the wrapped sink itself while it
 * is being drained (e.g. the MQTT client logging "Published to ...") are
 * dropped instead of re-enqueued, preventing 1:1 log amplification loops.
 *
 * @copyright Copyright (c) 2026 LopCore Contributors
 * @license MIT License
 */

#pragma once

#include <atomic>
#include <cstdint>
#include <deque>
#include <memory>
#include <mutex>
#include <string>

#include <esp_err.h>

#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "freertos/task.h"

#include "log_sink.hpp"

namespace lopcore
{

/**
 * @brief Configuration for QueuedSink
 */
struct QueuedSinkConfig
{
    size_t maxQueuedMessages = 64; ///< Bounded queue depth; overflow drops the oldest entry
    uint32_t drainPeriodMs = 100;  ///< Sleep between drain rounds of the built-in task
    size_t maxBatchPerDrain = 8;   ///< Messages forwarded to the inner sink per drain round
    uint32_t taskStackSize = 4096; ///< Stack size of the optional drain task
    int taskPriority = 3;          ///< Priority of the optional drain task
};

/**
 * @brief Enqueue-only decorator that drains into a wrapped sink
 *
 * Usage (firmware):
 * @code
 * auto sink = std::make_unique<QueuedSink>(
 *     std::make_unique<MqttLogSink>([client, topic](const std::string &line) {
 *         client->publishString(topic, line, mqtt::MqttQos::AT_MOST_ONCE, false);
 *     }));
 * sink->startDrainTask();
 * Logger::getInstance().addSink(std::move(sink));
 * @endcode
 */
class QueuedSink final : public ILogSink
{
public:
    explicit QueuedSink(std::unique_ptr<ILogSink> inner, QueuedSinkConfig config = {});
    ~QueuedSink() override;

    QueuedSink(const QueuedSink &) = delete;
    QueuedSink &operator=(const QueuedSink &) = delete;
    QueuedSink(QueuedSink &&) = delete;
    QueuedSink &operator=(QueuedSink &&) = delete;

    /**
     * @brief Enqueue a deep copy of the message; never blocks on I/O
     *
     * Safe to call while any foreign mutex (Logger, MQTT client, ...) is
     * held. Calls made from the thread currently draining (i.e. log lines
     * generated by the inner sink's own I/O) are counted and dropped.
     */
    void write(const LogMessage &msg) override;

    /**
     * @brief Deliberate no-op
     *
     * Logger::flush() holds the Logger mutex while calling sink->flush();
     * draining here would reintroduce the lock-order inversion this class
     * exists to remove. Use poll() to drain explicitly.
     */
    void flush() override;

    const char *getName() const override;

    /**
     * @brief Forward up to maxMessages queued entries to the inner sink
     *
     * Must be called outside any lock that the inner sink's I/O path could
     * contend with (in practice: from a plain application loop or the
     * built-in drain task).
     *
     * @return Number of messages forwarded
     */
    size_t poll(size_t maxMessages = SIZE_MAX);

    /**
     * @brief Start the optional background drain task
     */
    esp_err_t startDrainTask();

    /**
     * @brief Stop the background drain task (waits for it to exit)
     */
    void stopDrainTask();

    /**
     * @brief Number of messages dropped (overflow + drain-reentrancy)
     */
    uint32_t droppedCount() const;

private:
    /**
     * @brief Owned deep copy of a LogMessage (tag/message point into the
     *        Logger's stack buffer and are only valid during write())
     */
    struct OwnedLogMessage
    {
        LogLevel level;
        uint32_t timestamp_ms;
        std::string tag;
        std::string message;
    };

    static void drainTaskWrapper(void *pvParameters);
    void drainTask();

    std::unique_ptr<ILogSink> inner_;                  ///< Wrapped sink; only touched from poll()
    QueuedSinkConfig config_;                          ///< Configuration
    std::deque<OwnedLogMessage> queue_;                ///< Bounded FIFO, guarded by queueMutex_
    mutable std::mutex queueMutex_;                    ///< Guards queue_ and droppedCount_ only
    uint32_t droppedCount_ = 0;                        ///< Messages lost to overflow or drain re-entry
    TaskHandle_t drainTask_ = nullptr;                 ///< Optional background drain task
    std::atomic<bool> shouldRun_{false};               ///< Drain task loop control
    SemaphoreHandle_t taskStoppedSemaphore_ = nullptr; ///< Signals drain task exit
};

} // namespace lopcore
